# Bag of Words

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({"text":["people watch campusx","campusx watch campusx","people write comment","campusx write comment"],"output":[1,1,0,0]})

In [4]:
df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv = CountVectorizer()
bow = cv.fit_transform(df["text"])

In [8]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [9]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [13]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])