In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset, DataLoader

In [8]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [19]:
model = Sequential()
model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation="sigmoid"))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_2 (SimpleRNN)        │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[ 0.03033823, -0.70838076,  0.4012267 ],
       [-0.4719393 ,  0.7774661 ,  0.5630844 ],
       [ 0.17576867, -0.717538  , -0.43053415],
       [-0.570893  ,  0.30032033,  0.33030015],
       [-0.3323021 , -0.17704928, -0.17215478]], dtype=float32)

In [21]:
print(model.get_weights()[1].shape) # The Feedback Connection
model.get_weights()[1]

(3, 3)


array([[ 0.63366663,  0.7035757 , -0.32163313],
       [ 0.68027556, -0.3088076 ,  0.6647278 ],
       [-0.36836353,  0.640015  ,  0.67430633]], dtype=float32)

In [24]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [25]:
print(model.get_weights()[3].shape)
model.get_weights()[3]

(3, 1)


array([[-0.478159  ],
       [-0.7765149 ],
       [-0.15140474]], dtype=float32)

In [26]:
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)